// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCoolerChange();
void onHeaterChange();

String status;
float humidity;
float temperature;
bool cooler;
bool heater;

void initProperties(){

  ArduinoCloud.addProperty(status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(cooler, READWRITE, ON_CHANGE, onCoolerChange);
  ArduinoCloud.addProperty(heater, READWRITE, ON_CHANGE, onHeaterChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
